FROM debian

RUN apt update && \
    apt install -y openssh-server nano nginx

RUN mkdir /run/sshd && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'root:sam12345' | chpasswd

EXPOSE 22 80

#CMD ["/usr/sbin/sshd", "-D"]

CMD service ssh start && \
    #nginx -g "daemon off;"



