FROM debian

RUN apt update && \
    apt install -y bastet

#RUN mkdir /run/sshd && \
   # echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
  #  echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
 #   echo 'root:sam12345' | chpasswd

#EXPOSE 22 80

#CMD ["/usr/sbin/sshd", "-D"]

CMD ["/usr/games/bastet"]



